from collections.abc import (
    Hashable,
    ItemsView,
    Iterable,
    Iterator,
    KeysView,
    Mapping,
    MutableMapping,
    MutableSet,
    ValuesView,
)
from typing import Any, ClassVar, Generic, TypeVar, overload

from _typeshed import SupportsKeysAndGetItem
from typing_extensions import Self

_K = TypeVar("_K", bound=Hashable)
_V = TypeVar("_V")
_T = TypeVar("_T")
_K2 = TypeVar("_K2", bound=Hashable)
_V2 = TypeVar("_V2")

# The Elastic and Funnel surfaces are identical; each concrete class only
# fixes the backend. Methods that return the same parametrization use `Self`.
# Methods that re-parametrize (`fromkeys`, widening `|`, `union`, ...) return
# the base, mirroring how `dict.fromkeys` returns `dict` for subclasses.

class _MapBase(MutableMapping[_K, _V]):
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @overload
    def __init__(self, *, capacity: int = 0) -> None: ...
    @overload
    def __init__(
        self: _MapBase[str, _V], *, capacity: int = 0, **kwargs: _V
    ) -> None: ...
    @overload
    def __init__(
        self, other: SupportsKeysAndGetItem[_K, _V], *, capacity: int = 0
    ) -> None: ...
    @overload
    def __init__(
        self: _MapBase[str, _V],
        other: SupportsKeysAndGetItem[str, _V],
        *,
        capacity: int = 0,
        **kwargs: _V,
    ) -> None: ...
    @overload
    def __init__(
        self, other: Iterable[tuple[_K, _V]], *, capacity: int = 0
    ) -> None: ...
    @overload
    def __init__(
        self: _MapBase[str, _V],
        other: Iterable[tuple[str, _V]],
        *,
        capacity: int = 0,
        **kwargs: _V,
    ) -> None: ...
    @classmethod
    def with_options(
        cls,
        capacity: int = 0,
        reserve_exponent: int | None = None,
    ) -> Self: ...
    @overload
    @classmethod
    def fromkeys(
        cls, iterable: Iterable[_K2], value: None = None
    ) -> _MapBase[_K2, None]: ...
    @overload
    @classmethod
    def fromkeys(cls, iterable: Iterable[_K2], value: _V2) -> _MapBase[_K2, _V2]: ...
    @property
    def capacity(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: _K) -> _V: ...
    def __setitem__(self, key: _K, value: _V) -> None: ...
    def __delitem__(self, key: _K) -> None: ...
    def __iter__(self) -> Iterator[_K]: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def __or__(self, other: Mapping[_K, _V]) -> Self: ...
    @overload
    def __or__(self, other: Mapping[_K2, _V2]) -> _MapBase[_K | _K2, _V | _V2]: ...
    @overload
    def __ror__(self, other: Mapping[_K, _V]) -> Self: ...
    @overload
    def __ror__(self, other: Mapping[_K2, _V2]) -> _MapBase[_K | _K2, _V | _V2]: ...
    @overload  # type: ignore[misc]
    def __ior__(self, other: SupportsKeysAndGetItem[_K, _V]) -> Self: ...
    @overload
    def __ior__(self, other: Iterable[tuple[_K, _V]]) -> Self: ...
    @overload
    def get(self, key: _K) -> _V | None: ...
    @overload
    def get(self, key: _K, default: _V) -> _V: ...
    @overload
    def get(self, key: _K, default: _T) -> _V | _T: ...
    def clear(self) -> None: ...
    def keys(self) -> _KeysView[_K, _V]: ...
    def values(self) -> _ValuesView[_K, _V]: ...
    def items(self) -> _ItemsView[_K, _V]: ...
    @overload
    def update(
        self, other: SupportsKeysAndGetItem[_K, _V], /, **kwargs: _V
    ) -> None: ...
    @overload
    def update(self, other: Iterable[tuple[_K, _V]], /, **kwargs: _V) -> None: ...
    @overload
    def update(self, **kwargs: _V) -> None: ...
    @overload
    def pop(self, key: _K) -> _V: ...
    @overload
    def pop(self, key: _K, default: _V) -> _V: ...
    @overload
    def pop(self, key: _K, default: _T) -> _V | _T: ...
    def popitem(self) -> tuple[_K, _V]: ...
    @overload
    def setdefault(self: _MapBase[_K, _V | None], key: _K) -> _V | None: ...
    @overload
    def setdefault(self, key: _K, default: _V) -> _V: ...
    def copy(self) -> Self: ...

class ElasticHashMap(_MapBase[_K, _V]): ...
class FunnelHashMap(_MapBase[_K, _V]): ...

class _SetBase(MutableSet[_K]):
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __init__(self, iterable: Iterable[_K] = ..., *, capacity: int = 0) -> None: ...
    @classmethod
    def with_options(
        cls,
        capacity: int = 0,
        reserve_exponent: int | None = None,
    ) -> Self: ...
    @property
    def capacity(self) -> int: ...
    def __contains__(self, value: object) -> bool: ...
    def __iter__(self) -> Iterator[_K]: ...
    def __len__(self) -> int: ...
    def add(self, value: _K) -> None: ...
    def discard(self, value: _K) -> None: ...
    def copy(self) -> Self: ...
    def issubset(self, other: Iterable[Any]) -> bool: ...
    def issuperset(self, other: Iterable[Any]) -> bool: ...
    def union(self, *others: Iterable[_K2]) -> _SetBase[_K | _K2]: ...
    def intersection(self, *others: Iterable[Any]) -> Self: ...
    def difference(self, *others: Iterable[Any]) -> Self: ...
    def symmetric_difference(self, other: Iterable[_K2]) -> _SetBase[_K | _K2]: ...
    def update(self, *others: Iterable[_K]) -> None: ...
    def intersection_update(self, *others: Iterable[Any]) -> None: ...
    def difference_update(self, *others: Iterable[Any]) -> None: ...
    def symmetric_difference_update(self, other: Iterable[_K]) -> None: ...

class ElasticHashSet(_SetBase[_K]): ...
class FunnelHashSet(_SetBase[_K]): ...

# View types mirror dict_keys/dict_values/dict_items: parametrized over
# (_K, _V) for symmetry with the parent map even when only one is iterated.
# They are not module attributes; obtain instances via keys()/values()/items().

class _KeysView(KeysView[_K], Generic[_K, _V]):
    def __and__(self, other: Iterable[Any]) -> set[_K]: ...
    def __or__(self, other: Iterable[_T]) -> set[_K | _T]: ...
    def __sub__(self, other: Iterable[Any]) -> set[_K]: ...
    def __xor__(self, other: Iterable[_T]) -> set[_K | _T]: ...

class _ValuesView(ValuesView[_V], Generic[_K, _V]):
    def __contains__(self, value: object) -> bool: ...

class _ItemsView(ItemsView[_K, _V]):
    def __and__(self, other: Iterable[Any]) -> set[tuple[_K, _V]]: ...
    def __or__(self, other: Iterable[_T]) -> set[tuple[_K, _V] | _T]: ...
    def __sub__(self, other: Iterable[Any]) -> set[tuple[_K, _V]]: ...
