from collections.abc import (
    Hashable,
    ItemsView,
    Iterable,
    Iterator,
    KeysView,
    Mapping,
    MutableMapping,
    MutableSet,
    ValuesView,
)
from typing import Any, ClassVar, Generic, TypeVar, overload

from _typeshed import SupportsKeysAndGetItem
from typing_extensions import Self

K = TypeVar("K", bound=Hashable)
V = TypeVar("V")
T = TypeVar("T")
K2 = TypeVar("K2", bound=Hashable)
V2 = TypeVar("V2")

# The Elastic and Funnel surfaces are identical; each concrete class only
# fixes the backend. Methods that return the same parametrization use `Self`.
# Methods that re-parametrize (`fromkeys`, widening `|`, `union`, ...) return
# the base, mirroring how `dict.fromkeys` returns `dict` for subclasses.

class _MapBase(MutableMapping[K, V]):
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @overload
    def __init__(self, *, capacity: int = 0) -> None: ...
    @overload
    def __init__(self: _MapBase[str, V], *, capacity: int = 0, **kwargs: V) -> None: ...
    @overload
    def __init__(
        self, other: SupportsKeysAndGetItem[K, V], *, capacity: int = 0
    ) -> None: ...
    @overload
    def __init__(
        self: _MapBase[str, V],
        other: SupportsKeysAndGetItem[str, V],
        *,
        capacity: int = 0,
        **kwargs: V,
    ) -> None: ...
    @overload
    def __init__(self, other: Iterable[tuple[K, V]], *, capacity: int = 0) -> None: ...
    @overload
    def __init__(
        self: _MapBase[str, V],
        other: Iterable[tuple[str, V]],
        *,
        capacity: int = 0,
        **kwargs: V,
    ) -> None: ...
    @classmethod
    def with_options(
        cls,
        capacity: int = 0,
        reserve_exponent: int | None = None,
    ) -> Self: ...
    @overload
    @classmethod
    def fromkeys(
        cls, iterable: Iterable[K2], value: None = None
    ) -> _MapBase[K2, None]: ...
    @overload
    @classmethod
    def fromkeys(cls, iterable: Iterable[K2], value: V2) -> _MapBase[K2, V2]: ...
    @property
    def capacity(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __iter__(self) -> Iterator[K]: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def __or__(self, other: Mapping[K, V]) -> Self: ...
    @overload
    def __or__(self, other: Mapping[K2, V2]) -> _MapBase[K | K2, V | V2]: ...
    @overload
    def __ror__(self, other: Mapping[K, V]) -> Self: ...
    @overload
    def __ror__(self, other: Mapping[K2, V2]) -> _MapBase[K | K2, V | V2]: ...
    @overload  # type: ignore[misc]
    def __ior__(self, other: SupportsKeysAndGetItem[K, V]) -> Self: ...
    @overload
    def __ior__(self, other: Iterable[tuple[K, V]]) -> Self: ...
    @overload
    def get(self, key: K) -> V | None: ...
    @overload
    def get(self, key: K, default: V) -> V: ...
    @overload
    def get(self, key: K, default: T) -> V | T: ...
    def clear(self) -> None: ...
    def keys(self) -> _KeysView[K, V]: ...
    def values(self) -> _ValuesView[K, V]: ...
    def items(self) -> _ItemsView[K, V]: ...
    @overload
    def update(self, other: SupportsKeysAndGetItem[K, V], /, **kwargs: V) -> None: ...
    @overload
    def update(self, other: Iterable[tuple[K, V]], /, **kwargs: V) -> None: ...
    @overload
    def update(self, **kwargs: V) -> None: ...
    @overload
    def pop(self, key: K) -> V: ...
    @overload
    def pop(self, key: K, default: V) -> V: ...
    @overload
    def pop(self, key: K, default: T) -> V | T: ...
    def popitem(self) -> tuple[K, V]: ...
    @overload
    def setdefault(self: _MapBase[K, V | None], key: K) -> V | None: ...
    @overload
    def setdefault(self, key: K, default: V) -> V: ...
    def copy(self) -> Self: ...

class ElasticHashMap(_MapBase[K, V]): ...
class FunnelHashMap(_MapBase[K, V]): ...

class _SetBase(MutableSet[K]):
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __init__(self, iterable: Iterable[K] = ..., *, capacity: int = 0) -> None: ...
    @classmethod
    def with_options(
        cls,
        capacity: int = 0,
        reserve_exponent: int | None = None,
    ) -> Self: ...
    @property
    def capacity(self) -> int: ...
    def __contains__(self, value: object) -> bool: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    def add(self, value: K) -> None: ...
    def discard(self, value: K) -> None: ...
    def copy(self) -> Self: ...
    def issubset(self, other: Iterable[Any]) -> bool: ...
    def issuperset(self, other: Iterable[Any]) -> bool: ...
    def union(self, *others: Iterable[K2]) -> _SetBase[K | K2]: ...
    def intersection(self, *others: Iterable[Any]) -> Self: ...
    def difference(self, *others: Iterable[Any]) -> Self: ...
    def symmetric_difference(self, other: Iterable[K2]) -> _SetBase[K | K2]: ...
    def update(self, *others: Iterable[K]) -> None: ...
    def intersection_update(self, *others: Iterable[Any]) -> None: ...
    def difference_update(self, *others: Iterable[Any]) -> None: ...
    def symmetric_difference_update(self, other: Iterable[K]) -> None: ...

class ElasticHashSet(_SetBase[K]): ...
class FunnelHashSet(_SetBase[K]): ...

# View types mirror dict_keys/dict_values/dict_items: parametrized over
# (K, V) for symmetry with the parent map even when only one is iterated.
# They are not module attributes; obtain instances via keys()/values()/items().

class _KeysView(KeysView[K], Generic[K, V]):
    def __and__(self, other: Iterable[Any]) -> set[K]: ...
    def __or__(self, other: Iterable[T]) -> set[K | T]: ...
    def __sub__(self, other: Iterable[Any]) -> set[K]: ...
    def __xor__(self, other: Iterable[T]) -> set[K | T]: ...

class _ValuesView(ValuesView[V], Generic[K, V]):
    def __contains__(self, value: object) -> bool: ...

class _ItemsView(ItemsView[K, V]):
    def __and__(self, other: Iterable[Any]) -> set[tuple[K, V]]: ...
    def __or__(self, other: Iterable[T]) -> set[tuple[K, V] | T]: ...
    def __sub__(self, other: Iterable[Any]) -> set[tuple[K, V]]: ...
