from _typeshed import SupportsKeysAndGetItem
from collections.abc import (
    Hashable,
    Iterable,
    Iterator,
    ItemsView,
    KeysView,
    Mapping,
    MutableMapping,
    ValuesView,
)
from typing import Any, ClassVar, Generic, TypeVar, overload

K = TypeVar("K", bound=Hashable)
V = TypeVar("V")
T = TypeVar("T")
K2 = TypeVar("K2", bound=Hashable)
V2 = TypeVar("V2")

class ElasticHashMap(MutableMapping[K, V]):
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @overload
    def __init__(self, *, capacity: int = 0) -> None: ...
    @overload
    def __init__(
        self: ElasticHashMap[str, V], *, capacity: int = 0, **kwargs: V
    ) -> None: ...
    @overload
    def __init__(
        self, other: SupportsKeysAndGetItem[K, V], *, capacity: int = 0
    ) -> None: ...
    @overload
    def __init__(
        self: ElasticHashMap[str, V],
        other: SupportsKeysAndGetItem[str, V],
        *,
        capacity: int = 0,
        **kwargs: V,
    ) -> None: ...
    @overload
    def __init__(self, other: Iterable[tuple[K, V]], *, capacity: int = 0) -> None: ...
    @overload
    def __init__(
        self: ElasticHashMap[str, V],
        other: Iterable[tuple[str, V]],
        *,
        capacity: int = 0,
        **kwargs: V,
    ) -> None: ...
    @classmethod
    def with_options(
        cls,
        capacity: int = 0,
        reserve_fraction: float | None = None,
    ) -> ElasticHashMap[K, V]: ...
    @overload
    @classmethod
    def fromkeys(
        cls, iterable: Iterable[K2], value: None = None
    ) -> ElasticHashMap[K2, None]: ...
    @overload
    @classmethod
    def fromkeys(cls, iterable: Iterable[K2], value: V2) -> ElasticHashMap[K2, V2]: ...
    @property
    def capacity(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __iter__(self) -> Iterator[K]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    @overload
    def __or__(self, other: Mapping[K, V]) -> ElasticHashMap[K, V]: ...
    @overload
    def __or__(self, other: Mapping[K2, V2]) -> ElasticHashMap[K | K2, V | V2]: ...
    @overload
    def __ror__(self, other: Mapping[K, V]) -> ElasticHashMap[K, V]: ...
    @overload
    def __ror__(self, other: Mapping[K2, V2]) -> ElasticHashMap[K | K2, V | V2]: ...
    @overload  # type: ignore[misc]
    def __ior__(self, other: SupportsKeysAndGetItem[K, V]) -> ElasticHashMap[K, V]: ...
    @overload
    def __ior__(self, other: Iterable[tuple[K, V]]) -> ElasticHashMap[K, V]: ...
    @overload
    def get(self, key: K) -> V | None: ...
    @overload
    def get(self, key: K, default: V) -> V: ...
    @overload
    def get(self, key: K, default: T) -> V | T: ...
    def clear(self) -> None: ...
    def keys(self) -> elastic_keys[K, V]: ...
    def values(self) -> elastic_values[K, V]: ...
    def items(self) -> elastic_items[K, V]: ...
    @overload
    def update(self, other: SupportsKeysAndGetItem[K, V], /, **kwargs: V) -> None: ...
    @overload
    def update(self, other: Iterable[tuple[K, V]], /, **kwargs: V) -> None: ...
    @overload
    def update(self, **kwargs: V) -> None: ...
    @overload
    def pop(self, key: K) -> V: ...
    @overload
    def pop(self, key: K, default: V) -> V: ...
    @overload
    def pop(self, key: K, default: T) -> V | T: ...
    def popitem(self) -> tuple[K, V]: ...
    @overload
    def setdefault(self: ElasticHashMap[K, V | None], key: K) -> V | None: ...
    @overload
    def setdefault(self, key: K, default: V) -> V: ...
    def copy(self) -> ElasticHashMap[K, V]: ...

class FunnelHashMap(MutableMapping[K, V]):
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @overload
    def __init__(self, *, capacity: int = 0) -> None: ...
    @overload
    def __init__(
        self: FunnelHashMap[str, V], *, capacity: int = 0, **kwargs: V
    ) -> None: ...
    @overload
    def __init__(
        self, other: SupportsKeysAndGetItem[K, V], *, capacity: int = 0
    ) -> None: ...
    @overload
    def __init__(
        self: FunnelHashMap[str, V],
        other: SupportsKeysAndGetItem[str, V],
        *,
        capacity: int = 0,
        **kwargs: V,
    ) -> None: ...
    @overload
    def __init__(self, other: Iterable[tuple[K, V]], *, capacity: int = 0) -> None: ...
    @overload
    def __init__(
        self: FunnelHashMap[str, V],
        other: Iterable[tuple[str, V]],
        *,
        capacity: int = 0,
        **kwargs: V,
    ) -> None: ...
    @classmethod
    def with_options(
        cls,
        capacity: int = 0,
        reserve_fraction: float | None = None,
    ) -> FunnelHashMap[K, V]: ...
    @overload
    @classmethod
    def fromkeys(
        cls, iterable: Iterable[K2], value: None = None
    ) -> FunnelHashMap[K2, None]: ...
    @overload
    @classmethod
    def fromkeys(cls, iterable: Iterable[K2], value: V2) -> FunnelHashMap[K2, V2]: ...
    @property
    def capacity(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __iter__(self) -> Iterator[K]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    @overload
    def __or__(self, other: Mapping[K, V]) -> FunnelHashMap[K, V]: ...
    @overload
    def __or__(self, other: Mapping[K2, V2]) -> FunnelHashMap[K | K2, V | V2]: ...
    @overload
    def __ror__(self, other: Mapping[K, V]) -> FunnelHashMap[K, V]: ...
    @overload
    def __ror__(self, other: Mapping[K2, V2]) -> FunnelHashMap[K | K2, V | V2]: ...
    @overload  # type: ignore[misc]
    def __ior__(self, other: SupportsKeysAndGetItem[K, V]) -> FunnelHashMap[K, V]: ...
    @overload
    def __ior__(self, other: Iterable[tuple[K, V]]) -> FunnelHashMap[K, V]: ...
    @overload
    def get(self, key: K) -> V | None: ...
    @overload
    def get(self, key: K, default: V) -> V: ...
    @overload
    def get(self, key: K, default: T) -> V | T: ...
    def clear(self) -> None: ...
    def keys(self) -> funnel_keys[K, V]: ...
    def values(self) -> funnel_values[K, V]: ...
    def items(self) -> funnel_items[K, V]: ...
    @overload
    def update(self, other: SupportsKeysAndGetItem[K, V], /, **kwargs: V) -> None: ...
    @overload
    def update(self, other: Iterable[tuple[K, V]], /, **kwargs: V) -> None: ...
    @overload
    def update(self, **kwargs: V) -> None: ...
    @overload
    def pop(self, key: K) -> V: ...
    @overload
    def pop(self, key: K, default: V) -> V: ...
    @overload
    def pop(self, key: K, default: T) -> V | T: ...
    def popitem(self) -> tuple[K, V]: ...
    @overload
    def setdefault(self: FunnelHashMap[K, V | None], key: K) -> V | None: ...
    @overload
    def setdefault(self, key: K, default: V) -> V: ...
    def copy(self) -> FunnelHashMap[K, V]: ...

# View types mirror dict_keys/dict_values/dict_items: parametrized over
# (K, V) for symmetry with the parent map even when only one is iterated.

class elastic_keys(KeysView[K], Generic[K, V]):
    def __and__(self, other: Iterable[Any]) -> set[K]: ...
    def __or__(self, other: Iterable[T]) -> set[K | T]: ...
    def __sub__(self, other: Iterable[Any]) -> set[K]: ...
    def __xor__(self, other: Iterable[T]) -> set[K | T]: ...

class elastic_values(ValuesView[V], Generic[K, V]):
    def __contains__(self, value: object) -> bool: ...

class elastic_items(ItemsView[K, V]):
    def __and__(self, other: Iterable[Any]) -> set[tuple[K, V]]: ...
    def __or__(self, other: Iterable[T]) -> set[tuple[K, V] | T]: ...
    def __sub__(self, other: Iterable[Any]) -> set[tuple[K, V]]: ...

class funnel_keys(KeysView[K], Generic[K, V]):
    def __and__(self, other: Iterable[Any]) -> set[K]: ...
    def __or__(self, other: Iterable[T]) -> set[K | T]: ...
    def __sub__(self, other: Iterable[Any]) -> set[K]: ...
    def __xor__(self, other: Iterable[T]) -> set[K | T]: ...

class funnel_values(ValuesView[V], Generic[K, V]):
    def __contains__(self, value: object) -> bool: ...

class funnel_items(ItemsView[K, V]):
    def __and__(self, other: Iterable[Any]) -> set[tuple[K, V]]: ...
    def __or__(self, other: Iterable[T]) -> set[tuple[K, V] | T]: ...
    def __sub__(self, other: Iterable[Any]) -> set[tuple[K, V]]: ...
